language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - CC=g++-4.8 pip install ufal.udpipe
install:
  - python setup.py install
script:
  - python -m pytest
  - cd udapi/core/tests && ./external_tests.sh
